from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from dataclasses import asdict
from pathlib import Path

from vibeguard import __version__
from vibeguard.agents import ADAPTERS, get_agent, run_agent
from vibeguard.config import (
    ValidationError,
    default_config,
    load_config,
    project_config_path,
    set_config_value,
    write_project_config,
)
from vibeguard.governance_report import build_report, write_report
from vibeguard.security import policy_findings, scan_dependencies, scan_secrets
from vibeguard.ui.banner import print_banner
from vibeguard.ui.quickstart import print_quick_start

import typer
from rich.console import Console
from rich.table import Table

from vibeguard.core.builders import build_context, build_next_prompt, build_pack, build_plan, build_prompt
from vibeguard.core.diff_analyzer import analyze_diff
from vibeguard.core.report_generator import (
    ensure_vibeguard_dir,
    render_diff_report,
    render_risk_report,
    render_verification_report,
    write_text,
)
from vibeguard.core.risk_engine import Risk, analyze_risks
from vibeguard.core.scanner import scan_project
from vibeguard.core.token_packer import pack_files
from vibeguard.core.verifier import verify_project
from vibeguard.llm import (
    DEFAULT_MAX_TOKENS,
    DEFAULT_NVIDIA_MODEL,
    LLMConfigurationError,
    LLMRequestError,
    enhance_coding_prompt,
)
from vibeguard.utils.os_utils import get_os_name


def display_path(path: Path) -> str:
    return str(path)


def safe_path(p: Path | str) -> Path:
    p_str = str(p)
    if "\\" in p_str:
        p_str = p_str.replace("\\", "/")
    return Path(p_str)


app = typer.Typer(
    name="vibeguard",
    help="Trust, verification, and governance for AI-assisted software development.",
    no_args_is_help=False,
)
console = Console()
agents_app = typer.Typer(help="Detect and inspect supported coding agents.")
config_app = typer.Typer(help="Show, validate, and update VibeGuard configuration.")
ci_app = typer.Typer(help="Generate and run CI integration.")
precommit_app = typer.Typer(help="Manage the VibeGuard pre-commit hook.")
app.add_typer(agents_app, name="agents")
app.add_typer(config_app, name="config")
app.add_typer(ci_app, name="ci")
app.add_typer(precommit_app, name="precommit")


def version_callback(value: bool) -> None:
    if value:
        console.print(f"VibeGuard {__version__}")
        raise typer.Exit()


@app.callback(invoke_without_command=True)
def main(
    ctx: typer.Context,
    version: bool = typer.Option(
        None,
        "--version",
        "-V",
        callback=version_callback,
        is_eager=True,
        help="Show VibeGuard version and exit.",
    ),
) -> None:
    if ctx.invoked_subcommand is None:
        print_banner(console, compact=False)
        print_quick_start(console)


@app.command()
def init(
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Initialize .vibeguard in a project."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=False, project=project)
    out = ensure_vibeguard_dir(project)
    canonical_config = write_project_config(project, default_config(project))
    config = out / "config.yaml"
    if not config.exists():
        config.write_text(_default_config(project), encoding="utf-8")
    for name in ("context.md", "prompt.md", "task.md", "pack.md"):
        path = out / name
        if not path.exists():
            path.write_text(f"# {name}\n\nGenerated by VibeGuard.\n", encoding="utf-8")
    console.print("VibeGuard initialized successfully.")
    console.print(f"Created {display_path(canonical_config)}")


@app.command()
def scan(
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Scan project structure, stack, important files, and ignored folders."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    result = scan_project(project)
    _write_scan_cache(project, result)
    console.print(f"Project type: {result.detection.primary_type}")
    console.print(f"Package manager: {result.detection.package_manager or 'Unknown'}")
    console.print(f"Frameworks: {', '.join(result.detection.frameworks) or 'None detected'}")
    console.print(f"Languages: {', '.join(result.detection.languages) or 'None detected'}")
    console.print(f"Entry points: {', '.join(result.detection.entry_points) or 'None detected'}")
    console.print(f"Source directories: {', '.join(result.detection.source_dirs) or 'None detected'}")
    console.print(f"Test directories: {', '.join(result.detection.test_dirs) or 'None detected'}")
    console.print(f"Dependency manifests: {', '.join(result.detection.manifests) or 'None detected'}")
    console.print(f"Test tools: {', '.join(result.detection.test_tools) or 'None detected'}")
    console.print(f"Lint tools: {', '.join(result.detection.lint_tools) or 'None detected'}")
    console.print(f"Type tools: {', '.join(result.detection.type_tools) or 'None detected'}")
    table = Table(title="Detected important files")
    table.add_column("File")
    for file in result.important_files[:30]:
        table.add_row(file)
    console.print(table)
    if result.ignored:
        console.print("Ignored: " + ", ".join(result.ignored))


@app.command()
def context(
    goal_arg: str = typer.Argument(None, help="Goal for the AI coding task."),
    goal: str = typer.Option(None, "--goal", "-g", help="Goal for the AI coding task."),
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    max_tokens: int = typer.Option(8000, "--max-tokens", "-t", help="Context token budget."),
    task: str = typer.Option(None, "--task", help="Alias for the context goal."),
    budget: int = typer.Option(None, "--budget", help="Alias for --max-tokens."),
    output: Path = typer.Option(None, "--output", "-o", help="Optional output path."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Create an AI-readable context pack."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    resolved_goal = task or goal or goal_arg
    if not resolved_goal:
        console.print("ERROR: Missing option '--goal' / '-g' or positional argument.")
        raise typer.Exit(1)
    scan_result = scan_project(project)
    token_budget = budget or max_tokens
    pack_result = pack_files(project, scan_result, resolved_goal, token_budget)
    content = build_context(scan_result, resolved_goal, pack_result)
    if output:
        path = safe_path(output)
        path.write_text(content, encoding="utf-8")
    else:
        path = write_text(project, "context.md", content)
    console.print(f"Context written: {display_path(path)}")


@app.command()
def plan(
    goal_arg: str = typer.Argument(None, help="Goal for the AI coding task."),
    goal: str = typer.Option(None, "--goal", "-g", help="Goal for the AI coding task."),
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Turn a rough idea into a guarded implementation plan."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    resolved_goal = goal or goal_arg
    if not resolved_goal:
        console.print("ERROR: Missing option '--goal' / '-g' or positional argument.")
        raise typer.Exit(1)
    scan_result = scan_project(project)
    path = write_text(project, "task.md", build_plan(scan_result, resolved_goal))
    console.print(f"Plan written: {display_path(path)}")


@app.command()
def prompt(
    goal_arg: str = typer.Argument(None, help="Goal for the AI coding task."),
    goal: str = typer.Option(None, "--goal", "-g", help="Goal for the AI coding task."),
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    max_tokens: int = typer.Option(8000, "--max-tokens", "-t", help="Prompt file budget."),
    use_llm: bool = typer.Option(
        False,
        "--llm",
        help="Refine the generated prompt with NVIDIA GLM-5.2 (requires NVIDIA_API_KEY).",
    ),
    model: str = typer.Option(DEFAULT_NVIDIA_MODEL, "--model", help="NVIDIA NIM model name."),
    llm_max_tokens: int = typer.Option(
        DEFAULT_MAX_TOKENS,
        "--llm-max-tokens",
        min=1,
        help="Maximum tokens requested from the optional LLM.",
    ),
    agent: str = typer.Option("neutral", "--agent", help="Target agent style."),
    output: Path = typer.Option(None, "--output", "-o", help="Optional output path."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Generate a high-quality prompt for AI coding tools."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    resolved_goal = goal or goal_arg
    if not resolved_goal:
        console.print("ERROR: Missing option '--goal' / '-g' or positional argument.")
        raise typer.Exit(1)
    scan_result = scan_project(project)
    pack_result = pack_files(project, scan_result, resolved_goal, max_tokens)
    prompt_content = build_prompt(scan_result, resolved_goal, pack_result)
    if use_llm:
        console.print(f"Refining prompt with NVIDIA model: {model}")
        try:
            prompt_content = enhance_coding_prompt(
                prompt_content,
                model=model,
                max_tokens=llm_max_tokens,
            )
        except (LLMConfigurationError, LLMRequestError) as exc:
            console.print(f"ERROR: {exc}")
            raise typer.Exit(1) from exc
    if agent != "neutral":
        try:
            adapter = get_agent(agent)
        except ValueError as exc:
            console.print(f"ERROR: {exc}")
            raise typer.Exit(2) from exc
        prompt_content = f"<!-- Target agent: {adapter.display_name} -->\n" + prompt_content
    if output:
        path = safe_path(output)
        path.write_text(prompt_content, encoding="utf-8")
    else:
        path = write_text(project, "prompt.md", prompt_content)
    console.print(f"Prompt written: {display_path(path)}")


@app.command()
def pack(
    goal_arg: str = typer.Argument(None, help="Goal used for relevance scoring."),
    goal: str = typer.Option(None, "--goal", "-g", help="Goal used for relevance scoring."),
    max_tokens: int = typer.Option(8000, "--max-tokens", "-t", help="Maximum estimated token budget."),
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Create a token-aware context pack."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    resolved_goal = goal or goal_arg
    if not resolved_goal:
        console.print("ERROR: Missing option '--goal' / '-g' or positional argument.")
        raise typer.Exit(1)
    scan_result = scan_project(project)
    result = pack_files(project, scan_result, resolved_goal, max_tokens)
    path = write_text(project, "pack.md", build_pack(scan_result, resolved_goal, result, max_tokens))
    console.print(f"Pack written: {display_path(path)}")
    console.print(f"Estimated tokens: {result.estimated_tokens} / {max_tokens}")
    console.print("Included files:")
    for item in result.included:
        console.print(f"- {item.path}")
    console.print("Excluded files:")
    excluded_paths = [item.path for item in result.excluded[:20]] or ["node_modules", ".git", ".vibeguard", "assets", "dist", "build"]
    for excluded in excluded_paths:
        console.print(f"- {excluded}")


@app.command()
def verify(
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    quick: bool = typer.Option(False, "--quick", help="Run fast checks only."),
    full: bool = typer.Option(False, "--full", help="Run all detected checks."),
    json_output: bool = typer.Option(False, "--json", help="Print machine-readable results."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Run available verification checks without installing tools."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    scan_result = scan_project(project)
    if scan_result.detection.package_manager in ("yarn", "pnpm", "bun"):
        console.print(f"WARNING: Detected {scan_result.detection.package_manager} project. Automatic verification currently supports npm in MVP.")
    mode = "quick" if quick else "full"
    report = verify_project(project, scan_result.detection, mode=mode)
    path = write_text(project, "reports/verification_report.md", render_verification_report(report, scan_result.detection.primary_type, scan_result.detection.package_manager or "Unknown"))
    if json_output:
        console.print(json.dumps({"status": report.status, "checks": [asdict(item) for item in report.checks]}, indent=2))
    else:
        console.print("Verification Report")
        for check in report.checks:
            if check.status == "Passed":
                console.print(f"OK {check.name} ({check.duration:.2f}s)")
            elif check.status == "Skipped":
                console.print(f"WARNING {check.name} skipped: {check.details}")
            else:
                console.print(f"FAILED {check.name}: {check.details[:160]}")
        console.print(f"Report written: {display_path(path)}")
    if report.status == "Failed":
        raise typer.Exit(1)


@app.command()
def doctor(
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Check whether VibeGuard can run cleanly in the project."""
    root = safe_path(project).resolve()
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=False, project=root)
    scan_result = scan_project(root)
    detection = scan_result.detection
    warnings = 0
    failures = 0

    os_name = get_os_name().title()
    python_ver = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
    cwd = Path.cwd()
    project_path = root

    vibeguard_avail = "available" if shutil.which("vibeguard") else "missing"
    vig_avail = "available" if shutil.which("vig") else "missing"
    vbg_avail = "available" if shutil.which("vbg") else "missing"
    vg_path = shutil.which("vg")
    try:
        import vibeguard
        module_path = Path(vibeguard.__file__).resolve()
        if "site-packages" in str(module_path) or "dist-packages" in str(module_path):
            install_mode = "installed"
        else:
            install_mode = "editable"
    except Exception:
        install_mode = "unknown"

    git_avail = "available" if shutil.which("git") else "missing"
    node_avail = "available" if shutil.which("node") else "missing"
    npm_avail = "available" if shutil.which("npm") else "missing"
    python_exec = sys.executable
    pytest_avail = "available" if shutil.which("pytest") else "missing"
    ruff_avail = "available" if shutil.which("ruff") else "missing"
    nvidia_llm = "configured" if os.getenv("NVIDIA_API_KEY") else "missing (optional)"

    git_repo = "detected" if _has_git_repository(root) else "missing"
    pkg_json = "detected" if (root / "package.json").exists() else "missing"
    tsconfig = "detected" if (root / "tsconfig.json").exists() else "missing"
    vibeguard_folder = "detected" if (root / ".vibeguard").exists() else "missing"
    reports_folder = "detected" if (root / ".vibeguard" / "reports").exists() else "missing"

    console.print("VibeGuard Doctor")
    console.print("")
    console.print("System:")
    console.print(f"- OS: {os_name}")
    console.print(f"- Python: {python_ver}")
    console.print(f"- Current working directory: {display_path(cwd)}")
    console.print(f"- Project path: {display_path(project_path)}")
    console.print("")
    console.print("CLI:")
    console.print(f"- vibeguard command: {vibeguard_avail}")
    console.print(f"- vig command: {vig_avail}")
    console.print(f"- vbg command: {vbg_avail}")
    console.print(f"- Python executable: {display_path(Path(python_exec))}")
    console.print(f"- Package install mode: {install_mode}")
    console.print("")
    console.print("Tools:")
    console.print(f"- Git: {git_avail}")
    console.print(f"- Node: {node_avail}")
    console.print(f"- npm: {npm_avail}")
    console.print(f"- Python executable: {display_path(Path(python_exec))}")
    console.print(f"- pytest: {pytest_avail}")
    console.print(f"- ruff: {ruff_avail}")
    console.print(f"- NVIDIA LLM: {nvidia_llm}")
    console.print("")
    console.print("Project:")
    console.print(f"- Git repository: {git_repo}")
    console.print(f"- package.json: {pkg_json}")
    console.print(f"- tsconfig.json: {tsconfig}")
    console.print(f"- .vibeguard folder: {vibeguard_folder}")
    console.print(f"- reports folder: {reports_folder}")
    console.print(f"- Project type: {detection.primary_type}")
    console.print(f"- Package manager: {detection.package_manager or 'None'}")
    console.print("")
    console.print("Security:")
    console.print("- Sensitive files ignored: Yes")
    console.print("- Symlink traversal disabled: Yes")
    console.print("- Shell execution disabled: Yes")
    console.print("- Secret redaction enabled: Yes")
    console.print("")
    console.print("--------------------------------------------------")
    console.print("")

    if get_os_name() in ("windows", "macos", "linux"):
        console.print(f"OK OS detected: {os_name}")
    else:
        console.print(f"WARNING OS detected: {os_name}")
        warnings += 1

    console.print(f"OK Python detected: {python_ver}")

    if vibeguard_avail == "available":
        console.print("OK vibeguard command available")
    else:
        console.print("WARNING vibeguard command not found in PATH")
        console.print("Suggestion: run `pip install -e .` or use `pipx install -e .` in your workspace.")
        warnings += 1

    if vbg_avail == "available":
        console.print("OK vbg command available")
    else:
        console.print("WARNING vbg command not found in PATH")
        warnings += 1

    if get_os_name() == "linux" and vg_path:
        console.print("WARNING: Linux already provides a system command named 'vg'. Use 'vbg' instead.")

    if git_avail == "available":
        console.print("OK Git available")
    else:
        console.print("WARNING Git missing")
        warnings += 1

    if npm_avail == "available":
        console.print("OK npm available")
    else:
        console.print("WARNING npm missing")
        warnings += 1

    failures += _doctor_required("Git repository detected", git_repo == "detected")
    warnings += _doctor_warning("package.json detected", pkg_json == "detected" or "Node.js" not in detection.languages)
    warnings += _doctor_warning("TypeScript project detected", tsconfig == "detected")
    warnings += _doctor_warning(".vibeguard folder detected", vibeguard_folder == "detected")
    warnings += _doctor_warning("reports folder detected", reports_folder == "detected")

    if detection.primary_type != "Unknown":
        console.print(f"OK Project type detected: {detection.primary_type}")
    else:
        console.print("WARNING project type not detected")
        warnings += 1

    if detection.package_manager:
        console.print(f"OK Package manager detected: {detection.package_manager}")
    else:
        console.print("WARNING package manager not detected")
        warnings += 1

    for script in ("test", "lint", "typecheck"):
        if script in detection.scripts:
            console.print(f"OK {script} script available")
        else:
            console.print(f"WARNING {script} script missing")
            warnings += 1

    try:
        load_config(root)
        console.print("OK VibeGuard configuration valid")
    except (ValueError, ValidationError) as exc:
        console.print(f"FAILED VibeGuard configuration invalid: {exc}")
        failures += 1

    for adapter in ADAPTERS.values():
        label = "OK" if adapter.is_installed() else "WARNING"
        console.print(f"{label} Agent {adapter.display_name}: {adapter.resolve() or 'not installed'}")
    for tool in ("gitleaks", "semgrep", "mypy", "pyright", "black"):
        console.print(f"{'OK' if shutil.which(tool) else 'WARNING'} {tool}: {'available' if shutil.which(tool) else 'not installed'}")
    cache = ensure_vibeguard_dir(root) / "cache"
    console.print(f"{'OK' if os.access(cache, os.W_OK) else 'FAILED'} Cache writable: {cache}")

    console.print("OK secret redaction enabled")
    console.print("OK shell execution disabled")

    console.print("")
    if failures:
        console.print("Status: Not ready")
    elif warnings:
        console.print("Status: Ready with warnings")
    else:
        console.print("Status: Ready")


@app.command("all")
def run_all(
    goal_arg: str = typer.Argument(None, help="Goal for the full VibeGuard workflow."),
    goal: str = typer.Option(None, "--goal", "-g", help="Goal for the full VibeGuard workflow."),
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    max_tokens: int = typer.Option(8000, "--max-tokens", "-t", help="Maximum estimated token budget."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Run the complete MVP workflow."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=False, project=project)
    resolved_goal = goal or goal_arg
    if not resolved_goal:
        console.print("ERROR: Missing option '--goal' / '-g' or positional argument.")
        raise typer.Exit(1)
    console.print("Running VibeGuard workflow...")
    console.print("")
    if not project.exists():
        console.print(f"ERROR: Project path '{display_path(project)}' does not exist.")
        raise typer.Exit(1)

    try:
        ensure_vibeguard_dir(project)
    except PermissionError:
        console.print("ERROR: Permission denied. Cannot create .vibeguard folder.")
        raise typer.Exit(1)
    except Exception as e:
        console.print(f"ERROR: Cannot create .vibeguard folder. Reason: {e}")
        raise typer.Exit(1)

    scan_result = scan_project(project)
    if scan_result.detection.package_manager in ("yarn", "pnpm", "bun"):
        console.print(f"WARNING: Detected {scan_result.detection.package_manager} project. Automatic verification currently supports npm in MVP.")
    _write_scan_cache(project, scan_result)
    console.print("OK scan completed")

    context_pack = pack_files(project, scan_result, resolved_goal, max_tokens)
    write_text(project, "context.md", build_context(scan_result, resolved_goal, context_pack))
    console.print("OK context generated")

    write_text(project, "task.md", build_plan(scan_result, resolved_goal))
    console.print("OK plan generated")

    prompt_pack = pack_files(project, scan_result, resolved_goal, max_tokens)
    write_text(project, "prompt.md", build_prompt(scan_result, resolved_goal, prompt_pack))
    console.print("OK prompt generated")

    pack_result = pack_files(project, scan_result, resolved_goal, max_tokens)
    write_text(project, "pack.md", build_pack(scan_result, resolved_goal, pack_result, max_tokens))
    console.print("OK pack generated")

    verification = verify_project(project, scan_result.detection)
    write_text(project, "reports/verification_report.md", render_verification_report(verification, scan_result.detection.primary_type, scan_result.detection.package_manager or "Unknown"))
    if any(c.status == "Failed" for c in verification.checks):
        console.print("WARNING verify completed with failed checks")
    elif any(c.status == "Skipped" for c in verification.checks):
        console.print("WARNING verify completed with skipped checks")
    else:
        console.print("OK verification completed")

    diff = analyze_diff(project)
    if diff.status != "ok":
        if diff.status == "git_missing":
            console.print("WARNING Git not available. Skipping diff analysis.")
        elif diff.status == "not_git_repo":
            console.print("WARNING No Git repository detected. Skipping diff analysis.")
        elif diff.status == "no_commits":
            console.print("WARNING Git repository has no baseline commit. Skipping diff analysis.")
    else:
        write_text(project, "reports/diff_report.md", render_diff_report(diff))
        console.print("OK diff report generated")

        risk_report = analyze_risks(diff)
        write_text(project, "reports/risk_report.md", render_risk_report(risk_report))
        if any(r.severity in ("MEDIUM", "HIGH") for r in risk_report.risks):
            console.print("WARNING risk report generated with medium/high findings")
        else:
            console.print("OK risk report generated")

        risk_lines = [f"{risk.severity} {risk.path + ': ' if risk.path else ''}{risk.message}" for risk in risk_report.risks]
        write_text(project, "reports/next_prompt.md", build_next_prompt(risk_lines))
        console.print("OK next prompt generated")

    console.print("")
    console.print("Workflow complete.")
    console.print("Reports written to .vibeguard/reports")


@app.command("diff-explain")
def diff_explain(
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Explain uncommitted Git changes."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    diff = analyze_diff(project)
    if diff.status == "git_missing":
        console.print("Git not available. Skipping diff analysis.")
        return
    elif diff.status == "not_git_repo":
        console.print("No Git repository detected. Run `git init` to enable diff analysis.")
        return
    elif diff.status == "no_commits":
        console.print("Git repository has no baseline commit. Create an initial commit to enable meaningful diff analysis.")
        return

    path = write_text(project, "reports/diff_report.md", render_diff_report(diff))
    if not diff.changed_files:
        console.print("No uncommitted Git diff detected.")
    else:
        console.print("Changed files:")
        for changed in diff.changed_files:
            console.print(f"- {changed.path}")
        risk_notes = _diff_risk_notes([changed.path for changed in diff.changed_files])
        if risk_notes:
            console.print("Risk:")
            for note in risk_notes:
                console.print(f"- {note}")
    console.print(f"Report written: {display_path(path)}")


@app.command()
def risks(
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Show risky patterns in the current Git diff."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    diff = analyze_diff(project)
    if diff.status == "git_missing":
        console.print("Git not available. Skipping diff analysis.")
        return
    elif diff.status == "not_git_repo":
        console.print("No Git repository detected. Run `git init` to enable diff analysis.")
        return
    elif diff.status == "no_commits":
        console.print("Git repository has no baseline commit. Create an initial commit to enable meaningful diff analysis.")
        return

    report = analyze_risks(diff)
    path = write_text(project, "reports/risk_report.md", render_risk_report(report))
    console.print(f"Risk Level: {report.overall.title()}")
    for risk in report.risks:
        console.print(f"WARNING {risk.message}")
        if risk.path:
            console.print(f"File: {risk.path}")
        console.print(f"Reason: {_risk_reason(risk)}")
    console.print(f"Report written: {display_path(path)}")


@app.command("next-prompt")
def next_prompt(
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Generate the next best prompt after reviewing risky changes."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    diff = analyze_diff(project)
    if diff.status == "git_missing":
        console.print("Git not available. Skipping diff analysis.")
        return
    elif diff.status == "not_git_repo":
        console.print("No Git repository detected. Run `git init` to enable diff analysis.")
        return
    elif diff.status == "no_commits":
        console.print("Git repository has no baseline commit. Create an initial commit to enable meaningful diff analysis.")
        return

    report = analyze_risks(diff)
    risk_lines = [f"{risk.severity} {risk.path + ': ' if risk.path else ''}{risk.message}" for risk in report.risks]
    path = write_text(project, "reports/next_prompt.md", build_next_prompt(risk_lines))
    console.print(f"Next prompt written: {display_path(path)}")


@agents_app.command("list")
def agents_list() -> None:
    """List supported coding-agent adapters."""
    table = Table("Agent", "Executable", "Installed", "Version")
    for adapter in ADAPTERS.values():
        installed = adapter.is_installed()
        table.add_row(adapter.display_name, adapter.executable, "Yes" if installed else "No", adapter.get_version() or "—")
    console.print(table)


@agents_app.command("detect")
def agents_detect() -> None:
    """Detect installed coding agents."""
    installed = [adapter for adapter in ADAPTERS.values() if adapter.is_installed()]
    if not installed:
        console.print("No supported coding-agent CLI was detected.")
        raise typer.Exit(1)
    for adapter in installed:
        console.print(f"OK {adapter.display_name}: {adapter.resolve()}")


@agents_app.command("info")
def agents_info(name: str) -> None:
    """Show adapter metadata for one coding agent."""
    try:
        adapter = get_agent(name)
    except ValueError as exc:
        console.print(f"ERROR: {exc}")
        raise typer.Exit(2) from exc
    console.print(f"Name: {adapter.display_name}")
    console.print(f"Executable: {adapter.executable}")
    console.print(f"Installed: {'Yes' if adapter.is_installed() else 'No'}")
    console.print(f"Version: {adapter.get_version() or 'Unknown'}")
    console.print(f"Interactive: {'Yes' if adapter.interactive else 'No'}")
    console.print(f"Task mode: {'Yes' if adapter.non_interactive_args else 'No'}")


@config_app.command("show")
def config_show(project: Path = typer.Option(Path("."), "--project", "-p"), json_output: bool = typer.Option(False, "--json")) -> None:
    """Show the merged global, project, and environment configuration."""
    try:
        config = load_config(safe_path(project))
    except (ValueError, ValidationError) as exc:
        console.print(f"ERROR: Invalid configuration: {exc}")
        raise typer.Exit(2) from exc
    payload = config.model_dump()
    console.print(json.dumps(payload, indent=2) if json_output else __import__("yaml").safe_dump(payload, sort_keys=False))


@config_app.command("validate")
def config_validate(project: Path = typer.Option(Path("."), "--project", "-p")) -> None:
    """Validate the effective configuration."""
    try:
        load_config(safe_path(project))
    except (ValueError, ValidationError) as exc:
        console.print(f"FAIL {exc}")
        raise typer.Exit(2) from exc
    console.print(f"PASS {project_config_path(safe_path(project))}")


@config_app.command("set")
def config_set(key: str, value: str, project: Path = typer.Option(Path("."), "--project", "-p")) -> None:
    """Set one project configuration value using dotted notation."""
    try:
        set_config_value(safe_path(project), key, value)
    except (ValueError, ValidationError) as exc:
        console.print(f"ERROR: {exc}")
        raise typer.Exit(2) from exc
    console.print(f"Updated {key}")


@app.command("run")
def run_agent_command(
    agent: str,
    task: str = typer.Option(None, "--task", "-t"),
    project: Path = typer.Option(Path("."), "--project", "-p"),
    timeout: int = typer.Option(None, "--timeout", min=1),
    verify_after: bool = typer.Option(True, "--verify/--no-verify"),
) -> None:
    """Run a supported coding agent with a baseline and auditable postflight."""
    root = safe_path(project).resolve()
    try:
        adapter = get_agent(agent)
        session = run_agent(root, adapter, task=task, timeout=timeout)
    except (ValueError, FileNotFoundError) as exc:
        console.print(f"ERROR: {exc}")
        raise typer.Exit(2) from exc
    console.print(f"Agent exited with code {session.exit_code}; session {session.session_id}")
    blocked = _postflight(root, session.agent, task, session.files_changed) if verify_after else False
    if session.exit_code != 0 or blocked:
        raise typer.Exit(session.exit_code or 1)


@app.command("exec", context_settings={"allow_extra_args": True, "ignore_unknown_options": True})
def exec_agent_command(
    ctx: typer.Context,
    project: Path = typer.Option(Path("."), "--project", "-p"),
    verify_after: bool = typer.Option(True, "--verify/--no-verify"),
) -> None:
    """Pass arguments safely to a known coding-agent CLI: vig exec -- codex ..."""
    arguments = list(ctx.args)
    if not arguments:
        console.print("ERROR: Provide a supported agent command after `--`.")
        raise typer.Exit(2)
    executable, *extra = arguments
    try:
        adapter = get_agent(executable)
        session = run_agent(safe_path(project), adapter, extra_args=extra)
    except (ValueError, FileNotFoundError) as exc:
        console.print(f"ERROR: {exc}")
        raise typer.Exit(2) from exc
    blocked = _postflight(safe_path(project), session.agent, None, session.files_changed) if verify_after else False
    if session.exit_code != 0 or blocked:
        raise typer.Exit(session.exit_code or 1)


@app.command("risk")
def risk_command(project: Path = typer.Option(Path("."), "--project", "-p"), json_output: bool = typer.Option(False, "--json")) -> None:
    """Run deterministic policy and change-risk analysis."""
    root = safe_path(project).resolve()
    diff = analyze_diff(root)
    if diff.status != "ok":
        console.print(f"ERROR: Git diff unavailable ({diff.status}).")
        raise typer.Exit(2)
    findings = policy_findings(diff, load_config(root))
    score = min(100, sum({"INFO": 1, "LOW": 5, "MEDIUM": 15, "HIGH": 30, "CRITICAL": 50}.get(item.severity, 0) for item in findings))
    if json_output:
        console.print(json.dumps({"score": score, "findings": [asdict(item) for item in findings]}, indent=2))
    else:
        console.print(f"Risk score: {score}/100")
        for finding in findings:
            console.print(f"{finding.severity} {finding.file}: {finding.message}")
    if score >= load_config(root).policies.blocking_score:
        raise typer.Exit(1)


@app.command("secrets")
def secrets_command(project: Path = typer.Option(Path("."), "--project", "-p"), json_output: bool = typer.Option(False, "--json")) -> None:
    """Scan repository text for redacted secret-like values."""
    findings = scan_secrets(safe_path(project).resolve())
    if json_output:
        console.print(json.dumps([asdict(item) for item in findings], indent=2))
    elif not findings:
        console.print("PASS No secret-like values detected.")
    else:
        for item in findings:
            console.print(f"{item.severity} {item.file}:{item.line} {item.message}")
            console.print(f"Remediation: {item.remediation}")
    if findings:
        raise typer.Exit(1)


@app.command("deps")
def deps_command(project: Path = typer.Option(Path("."), "--project", "-p"), json_output: bool = typer.Option(False, "--json")) -> None:
    """Analyze dependency manifests and current manifest changes."""
    root = safe_path(project).resolve()
    diff = analyze_diff(root)
    findings = scan_dependencies(root, diff if diff.status == "ok" else None)
    if json_output:
        console.print(json.dumps([asdict(item) for item in findings], indent=2))
    elif not findings:
        console.print("PASS No suspicious dependency finding detected.")
    else:
        for item in findings:
            console.print(f"{item.severity} {item.file}: {item.message}")


@app.command("explain")
def explain_command(project: Path = typer.Option(Path("."), "--project", "-p")) -> None:
    """Explain current changes for developers, business owners, and reviewers."""
    root = safe_path(project).resolve()
    diff = analyze_diff(root)
    if diff.status != "ok":
        console.print(f"ERROR: Git diff unavailable ({diff.status}).")
        raise typer.Exit(2)
    findings = policy_findings(diff, load_config(root))
    lines = [
        "# VibeGuard Change Explanation", "", "## What changed",
        *(f"- {item.status.title()}: `{item.path}` (+{item.additions}/-{item.deletions})" for item in diff.changed_files),
        "", "## Behavioral impact", "- Review changed modules for user-visible behavior and data-flow changes.",
        "", "## Security impact", *(f"- {item.severity}: {item.message} (`{item.file}`)" for item in findings),
        "", "## Compatibility and test impact", "- Confirm public interfaces, configuration and tests remain compatible.",
        "", "## Recommended action", "- Resolve findings, run `vig verify`, then generate `vig report`.",
    ]
    path = write_text(root, "reports/explanation.md", "\n".join(lines) + "\n")
    console.print(f"Explanation written: {path}")


@app.command("report")
def report_command(
    project: Path = typer.Option(Path("."), "--project", "-p"),
    format_name: str = typer.Option("markdown", "--format", "-f"),
) -> None:
    """Generate a consolidated Markdown, JSON, or SARIF governance report."""
    root = safe_path(project).resolve()
    report = _current_report(root)
    try:
        path = write_report(root, report, format_name)
    except ValueError as exc:
        console.print(f"ERROR: {exc}")
        raise typer.Exit(2) from exc
    console.print(f"Decision: {report.decision}")
    console.print(f"Risk score: {report.score}/100")
    console.print(f"Report written: {path}")
    if report.decision == "BLOCKED":
        raise typer.Exit(1)


@app.command("next")
def next_command(project: Path = typer.Option(Path("."), "--project", "-p")) -> None:
    """Generate a scoped corrective prompt from current checks and findings."""
    root = safe_path(project).resolve()
    report = _current_report(root)
    failures = [item for item in report.checks if item.get("status") == "Failed"]
    lines = ["# VibeGuard Corrective Prompt", "", "Correct only the failures and risks listed below.", "", "## Exact failures"]
    lines.extend(f"- {item.get('name')}: {str(item.get('details', ''))[:300]}" for item in failures)
    lines.extend(["", "## Risk findings"])
    lines.extend(f"- {item.severity} `{item.file}`: {item.message}" for item in report.findings)
    lines.extend(["", "## Scope", "- Do not touch unrelated or protected files.", "- Add or update tests for corrected behavior.", "- Run the failed commands and `vig verify`.", "", "## Acceptance criteria", "- All blocking checks pass.", "- High/critical findings are resolved or explicitly reviewed.", "- Completion report lists changed files and tests."])
    path = write_text(root, "reports/next-prompt.md", "\n".join(lines) + "\n")
    console.print(f"Next prompt written: {path}")


@ci_app.command("generate")
def ci_generate(provider: str, project: Path = typer.Option(Path("."), "--project", "-p")) -> None:
    """Generate a local-only GitHub Actions or GitLab CI workflow."""
    root = safe_path(project).resolve()
    if provider == "github":
        path = root / ".github" / "workflows" / "vibeguard.yml"
        content = """name: VibeGuard\non: [push, pull_request]\npermissions:\n  contents: read\n  security-events: write\njobs:\n  verify:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-python@v5\n        with:\n          python-version: '3.11'\n      - run: pip install vibegaurd-cli\n      - run: vig ci check\n      - if: always()\n        uses: github/codeql-action/upload-sarif@v3\n        with:\n          sarif_file: .vibeguard/reports/vibeguard-report.sarif\n"""
    elif provider == "gitlab":
        path = root / ".gitlab-ci.yml"
        content = """vibeguard:\n  image: python:3.11\n  script:\n    - pip install vibegaurd-cli\n    - vig ci check\n  artifacts:\n    when: always\n    paths:\n      - .vibeguard/reports/\n"""
    else:
        console.print("ERROR: Provider must be github or gitlab.")
        raise typer.Exit(2)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        console.print(f"ERROR: Refusing to overwrite {path}")
        raise typer.Exit(1)
    path.write_text(content, encoding="utf-8")
    console.print(f"Generated {path}")


@ci_app.command("check")
def ci_check(project: Path = typer.Option(Path("."), "--project", "-p")) -> None:
    """Run verification/risk and always emit JSON, Markdown and SARIF reports."""
    root = safe_path(project).resolve()
    report = _current_report(root)
    for format_name in ("markdown", "json", "sarif"):
        write_report(root, report, format_name)
    console.print(f"Decision: {report.decision}")
    if report.decision in {"BLOCKED", "REVIEW_REQUIRED"}:
        raise typer.Exit(1)


@precommit_app.command("install")
def precommit_install(project: Path = typer.Option(Path("."), "--project", "-p")) -> None:
    """Install a guarded local Git pre-commit hook without overwriting an existing hook."""
    root = safe_path(project).resolve()
    hook = root / ".git" / "hooks" / "pre-commit"
    if not hook.parent.exists():
        console.print("ERROR: This is not a Git repository.")
        raise typer.Exit(2)
    if hook.exists():
        console.print(f"ERROR: Refusing to overwrite existing hook: {hook}")
        raise typer.Exit(1)
    hook.write_text("#!/bin/sh\nexec vig verify --quick --project .\n", encoding="utf-8")
    hook.chmod(0o755)
    console.print(f"Installed {hook}")


@app.command("shell")
def shell_command(project: Path = typer.Option(Path("."), "--project", "-p")) -> None:
    """Open the lightweight VibeGuard workflow shell after wrapper mode is available."""
    root = safe_path(project).resolve()
    selected = load_config(root).agents.default
    console.print("VibeGuard Safe Session")
    console.print(f"Repository: {root.name}")
    console.print(f"Policy: {load_config(root).policies.risk_level}")
    console.print(f"Intelligence: {load_config(root).intelligence.model}")
    while True:
        try:
            value = input("vig> ").strip()
        except (EOFError, KeyboardInterrupt):
            console.print("")
            return
        if value in {"exit", "quit"}:
            return
        if value == "agents":
            console.print(", ".join(f"{name}{'*' if name == selected else ''}" for name in ADAPTERS))
        elif value.startswith("use "):
            name = value[4:].strip()
            try:
                get_agent(name)
                selected = name
                console.print(f"Using {name}")
            except ValueError as exc:
                console.print(f"ERROR: {exc}")
        elif value == "run":
            try:
                session = run_agent(root, get_agent(selected))
                console.print(f"Session {session.session_id} exited {session.exit_code}")
            except (ValueError, FileNotFoundError) as exc:
                console.print(f"ERROR: {exc}")
        elif value == "verify":
            report = _current_report(root)
            console.print(f"Decision: {report.decision}")
        elif value in {"explain", "report", "next", "context", "plan"}:
            console.print(f"Run `vig {value}` outside the shell with any required task arguments.")
        else:
            console.print("Commands: agents, use <agent>, run, verify, explain, report, next, exit")


def _current_report(root: Path):
    scan_result = scan_project(root)
    verification = verify_project(root, scan_result.detection)
    diff = analyze_diff(root)
    findings = scan_secrets(root) + scan_dependencies(root, diff if diff.status == "ok" else None)
    changed_files: list[str] = []
    if diff.status == "ok":
        findings += policy_findings(diff, load_config(root))
        changed_files = [item.path for item in diff.changed_files]
    latest = ensure_vibeguard_dir(root) / "sessions" / "latest.json"
    session = json.loads(latest.read_text(encoding="utf-8")) if latest.exists() else {}
    checks = [asdict(item) for item in verification.checks]
    return build_report(root, findings=findings, checks=checks, files_changed=changed_files, agent=session.get("agent"), task=session.get("task"))


def _postflight(root: Path, agent: str, task: str | None, session_files: list[str]) -> bool:
    report = _current_report(root)
    if session_files and not report.files_changed:
        report = build_report(root, findings=report.findings, checks=report.checks, files_changed=session_files, agent=agent, task=task)
    for format_name in ("markdown", "json"):
        write_report(root, report, format_name)
    console.print(f"Postflight decision: {report.decision} (risk {report.score}/100)")
    return report.decision == "BLOCKED"


def _doctor_required(label: str, ok: bool) -> int:
    if ok:
        console.print(f"OK {label}")
        return 0
    console.print(f"FAILED {label}")
    return 1


def _doctor_warning(label: str, ok: bool) -> int:
    if ok:
        console.print(f"OK {label}")
        return 0
    console.print(f"WARNING {label}")
    return 1


def _has_git_repository(root: Path) -> bool:
    if (root / ".git").exists():
        return True
    try:
        result = subprocess.run(["git", "rev-parse", "--is-inside-work-tree"], cwd=root, text=True, capture_output=True, check=False)
    except FileNotFoundError:
        return False
    return result.returncode == 0 and result.stdout.strip() == "true"


def _diff_risk_notes(paths: list[str]) -> list[str]:
    lower_paths = [path.lower() for path in paths]
    notes: list[str] = []
    if any("auth" in path for path in lower_paths):
        notes.append("Auth-related file changed")
    if paths and not any(any(term in path for term in (".test.", ".spec.", "__tests__", "/tests/", "\\tests\\")) for path in lower_paths):
        notes.append("No test file changed")
    return notes


def _risk_reason(risk: Risk) -> str:
    lower = risk.message.lower()
    if "auth" in lower:
        return "auth-related files require manual review"
    if "no test" in lower:
        return "feature code changed without test update"
    if "secret" in lower:
        return "changed code contains possible hardcoded secret/API key/token"
    if "dependency" in lower or "lockfile" in lower:
        return "dependency changes can affect runtime and supply-chain safety"
    if "deleted" in lower:
        return "deleted files may break imports or behavior"
    if "large" in lower:
        return "large diffs are harder to review and may include unrelated edits"
    return risk.message.rstrip(".")


def _write_scan_cache(project: Path, result) -> None:
    out = ensure_vibeguard_dir(project)
    data = {
        "type": result.detection.primary_type,
        "languages": result.detection.languages,
        "frameworks": result.detection.frameworks,
        "files": result.files,
        "important_files": result.important_files,
        "ignored": result.ignored,
    }
    (out / "cache" / "scan.json").write_text(json.dumps(data, indent=2), encoding="utf-8")


def _default_config(project: Path) -> str:
    name = Path(project).resolve().name
    return f'''project_name: "{name}"
ignore:
  - node_modules
  - .git
  - dist
  - build
  - .next
  - venv
  - __pycache__
protected_files:
  - ".env"
  - ".env.production"
  - "package-lock.json"
  - "yarn.lock"
  - "pnpm-lock.yaml"
  - "migrations/**"
risky_paths:
  - auth
  - payment
  - billing
  - security
  - middleware
  - permissions
  - admin
  - database
  - migrations
verification:
  python:
    - "python -m compileall ."
    - "pytest"
    - "ruff check ."
  node:
    - "npm test"
    - "npm run lint"
    - "npm run typecheck"
token_budget:
  default_max_tokens: 8000
'''


if __name__ == "__main__":
    app()
